using System.Reflection;

// NB! this file is automatically generated. All manual changes will be lost on build.
// Check ~/_tools/Nortal.Utilities.AssemblyVersioning.props file for other available algorithms and supported attributes.

// Generated based on assembly version: 0.9.0.0
[assembly: AssemblyInformationalVersion("0.9.0")] // algorithm: NugetSemanticVersionGenerator
[assembly: AssemblyConfiguration("Release (on UTC2014-02-05T15:06:56 by imrep at DELL472)")] // algorithm: HumanReadableBuildInfoGenerator
