using System.Reflection;

// NB! this file is automatically generated. All manual changes will be lost on build.
// Check ~/_tools/Nortal.Utilities.AssemblyVersioning.props file for other available algorithms and supported attributes.

// Generated based on assembly version: 0.9.2.0
[assembly: AssemblyInformationalVersion(@"0.9.2-Debug-20161022-0859")] // algorithm: NugetSemanticVersionGenerator
[assembly: AssemblyConfiguration(@"Debug (on UTC2016-10-22T08:59:55 by Imre at BLACKBOX)")] // algorithm: HumanReadableBuildInfoGenerator
